### ISSUE TITLE
Найденные ошибки в браузерном JS

### ISSUE THREAD

**Issue by dolho** [DevInCube/backenddev-lab5-websocket-client#1]
1) В качестве телеграм логина, код принимает значение из поля для обычного логина (676 строка)
2) Object.SetInstanseOf -- несуществующий метод (помогла замена на Object.setPrototypeOf) (494 строка)
3)  MessageTypes:
    CLIENT_JOIN_ROOM: "remove-room", - должно быть  join-room (56 строка)
    CLIENT_LEAVE_ROOM: "remove-room", - должно быть leave-room (57 строка)
4) При выходе из комнаты (кнопка 'Leave room') не отправляет 'leave-room'.
   Нельзя отправить пустую комнату в ответ на leave-room (не проходит validateRoom). Единственный способ выйти из начальной комнаты это перейти в другую. 
5) getMessages -- функция нигде не вызывается (нужен вызов в setJoinedRoom())
6) CLIENT_RENAME_ROOM вместо CLIENT_REMOVE_ROOM (В функции removeRoomAppMessage())

**Comment by DevInCube** [comment]
Дуже дякую! Також можете наступного разу присилати PR, якщо буде зручно.
